// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daiyrwxcsqvbbntzjdzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhaXlyd3hjc3F2YmJudHpqZHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyNDA5NzEsImV4cCI6MjA4NzgxNjk3MX0.vfEp5rvAV1piVITaOQLKPvySgeNg0x49b1meXy_gfec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});